# Generated by Django 5.1.5 on 2025-01-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volonteer', '0002_alter_user_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
