# Generated by Django 5.1.5 on 2025-02-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volonteer', '0002_alter_task_description_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskparticipation',
            old_name='is_participating',
            new_name='is_participated',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_width',
        ),
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='volonteer.achievement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('volunteer', 'Volunteer'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], db_index=True, max_length=15, null=True),
        ),
    ]
